name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node dependencies 📦
        run: pnpm install --no-frozen-lockfile

      - name: Build Web App 🏗️
        run: |
          pnpm --filter web build
          cp apps/web/dist/index.html apps/web/dist/404.html

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/web/dist
          branch: gh-pages
          clean: true
